slack:
  client:
    clientId: "3490096050.217656305830"
    clientSecret: "46493610859295f7621f62a4be60d860"
    accessTokenUri: https://slack.com/api/oauth.access
    userAuthorizationUri: https://slack.com/oauth/authorize
    tokenName: token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: identity.basic
  resource:
    userInfoUri: https://slack.com/api/users.identity?token=
logging:
  level:
    org.springframework.security: WARN