slack:
  client:
    clientId: "225187789888.225193189936"
    clientSecret: "5104fde84aaf467439cdd820dea14c7e"
    accessTokenUri: https://slack.com/api/oauth.access
    userAuthorizationUri: https://slack.com/oauth/authorize
    tokenName: token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: identity.basic
  resource:
    userInfoUri: https://slack.com/api/users.identity?token=
logging:
  level:
    org.springframework.security: DEBUG